language: node_js
sudo: false
dist: xenial
node_js: '10'
addons:
  firefox: "71.0"
  chrome: stable
cache:
  directories:
  - node_modules
services:
  - xvfb
matrix:
  fast_finish: true
  allow_failures:
    - env: JOB=benchmark

  include:
    - env: JOB=benchmark
      script:
        - ./travis-bench.sh
